#!/usr/bin/env bash

DOCKER_GID=$(ls -lan /var/run/docker.sock  | awk '{print $4}')
# DOCKER_GROUP=$(ls -la /var/run/docker.sock  | awk '{print $4}')

echo "GID: $DOCKER_GID"
# echo "GROUP: $DOCKER_GROUP"

if (which docker) ; then
    echo "Docker is already installed or bind mounted into container"

    if ! (getent group "$DOCKER_GID") ; then
        echo "Creating docker group with GID $DOCKER_GID"
        # addgroup --gid "$DOCKER_GID" "$DOCKER_GROUP"
        addgroup --gid "$DOCKER_GID" docker
    fi

    # if ! (id -nG jenkins | grep -qw "$DOCKER_GROUP") ; then
    if ! (id -nG jenkins | grep -qw docker) ; then
        # echo "Adding jenkins user to group $DOCKER_GROUP with GID $DOCKER_GID"
        echo "Adding jenkins user to group docker with GID $DOCKER_GID"
        # adduser jenkins "$DOCKER_GROUP"
        adduser jenkins docker
    fi
else
    echo "Docker is not present, going to install it"
    # TODO, not needed for now
fi

# exec jenkins-slave "$command"
command="$@"
echo "COMMAND: $command"

# TODO, maybe better?
# exec su jenkins -s "$SHELL" -c "'jenkins-slave $@'"
# exec su $JUSER -c "/bin/tini -- /usr/local/bin/jenkins.sh"

su jenkins -s /bin/bash -c 'exec jenkins-slave "$@"' -- bash $command
